// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handlers

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1ff466a0DecodeGithubComAlexeySergeychukLinkshortenerInternalAppHandlers(in *jlexer.Lexer, out *URLResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "result":
			out.Result = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1ff466a0EncodeGithubComAlexeySergeychukLinkshortenerInternalAppHandlers(out *jwriter.Writer, in URLResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"result\":"
		out.RawString(prefix[1:])
		out.String(string(in.Result))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v URLResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1ff466a0EncodeGithubComAlexeySergeychukLinkshortenerInternalAppHandlers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v URLResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1ff466a0EncodeGithubComAlexeySergeychukLinkshortenerInternalAppHandlers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *URLResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1ff466a0DecodeGithubComAlexeySergeychukLinkshortenerInternalAppHandlers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *URLResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1ff466a0DecodeGithubComAlexeySergeychukLinkshortenerInternalAppHandlers(l, v)
}
